
import $ from 'jquery';
import * as uiCommon from './common.js';
import { renderCategoryForm } from './forms.js';

export function getRoleBadgeClass(role) { switch (role) { case 'admin': return 'danger'; case 'editor': return 'warning'; case 'author': return 'info'; case 'reader': return 'secondary'; default: return 'light'; } }
export function renderCategoryAdminList(categories) { const contentArea = uiCommon.contentArea; const categoryFormHtml = renderCategoryForm(); contentArea.html(` <div class="d-flex justify-content-between align-items-center mb-3"> <h2>Categories</h2> <button class="btn btn-primary" id="add-category-btn"><i class="bi bi-plus-circle"></i> Add</button> </div> <div id="category-form-container" class="mb-3" style="display: none;"> ${categoryFormHtml} </div> <table class="table table-striped table-hover align-middle"> <thead> <tr> <th>ID</th> <th>Name</th> <th>Slug</th> <th class="text-end">Actions</th> </tr> </thead> <tbody id="category-list"> ${categories?.length ? categories.map(c => ` <tr data-id="${c.id}" data-name="${c.name}" data-slug="${c.slug}"> <td>${c.id}</td> <td class="cat-name">${c.name}</td> <td class="cat-slug">${c.slug}</td> <td class="text-end"> <button class="btn btn-sm btn-warning btn-edit-category me-1" data-id="${c.id}"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-danger btn-delete-category" data-id="${c.id}"><i class="bi bi-trash"></i></button> </td> </tr>`).join('') : `<tr><td colspan="4" class="text-center text-muted">None found.</td></tr>` } </tbody> </table> `); }
export function renderUserAdminList(users) { const contentArea = uiCommon.contentArea; contentArea.html(` <div class="d-flex justify-content-between align-items-center mb-3"> <h2>Users</h2> <a href="/admin/users/user/add/" target="_blank" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Add (Admin)</a> </div> <p class="text-muted small">Full management via <a href="/admin/users/" target="_blank">Django Admin</a>.</p> <table class="table table-striped table-hover align-middle"> <thead> <tr> <th>ID</th> <th>Username</th> <th>Email</th> <th>Role</th> <th>Staff</th> <th>Joined</th> <th class="text-end">Actions</th> </tr> </thead> <tbody> ${users?.length ? users.map(u => ` <tr> <td>${u.id}</td> <td>${u.username}</td> <td>${u.email||'-'}</td> <td><span class="badge bg-${getRoleBadgeClass(u.role)}">${u.role}</span></td> <td>${u.is_staff ? '<i class="bi bi-check-circle-fill text-success"></i> Yes' : '<i class="bi bi-x-circle text-danger"></i> No'}</td> <td>${new Date(u.date_joined).toLocaleDateString()}</td> <td class="text-end"> <a href="/admin/users/user/${u.id}/change/" target="_blank" class="btn btn-sm btn-secondary"><i class="bi bi-pencil-square"></i></a> </td> </tr> `).join('') : `<tr><td colspan="7" class="text-center text-muted">None found.</td></tr>`} </tbody> </table> <div id="pagination-controls"></div> `); }
export function renderTagAdminList(tags) { const contentArea = uiCommon.contentArea; contentArea.html(` <div class="d-flex justify-content-between align-items-center mb-3"> <h2>Tags</h2> <span class="text-muted small">Managed via posts</span> </div> <div class="d-flex flex-wrap gap-2"> ${tags?.length ? tags.map(t => ` <a href="#posts/by_tag/${t.name}" class="tag fs-6" title="${t.post_count} posts"> ${t.name} <span class="badge bg-secondary rounded-pill ms-1">${t.post_count}</span> </a> `).join('') : '<p class="text-muted">None found.</p>'} </div> <div id="pagination-controls" class="mt-3"></div> `); }
