
import $ from 'jquery';
import { apiRequest } from '../core/api.js';
import * as auth from '../core/auth.js';
import { showAlert } from '../ui/common.js';
import { renderCommentForm } from '../ui/comments.js';
import { navigateTo, loadComments } from '../router.js';

export function handleCommentSubmit(event) { event.preventDefault(); if (!auth.checkAuthStatus()) { navigateTo('#login'); return; } const form = $(event.target); const postId = form.data('post-id'); const parentId = form.data('parent-id') || null; const content = form.find('textarea[name="content"]').val(); if (!postId || !content.trim()) { showAlert('Comment cannot be empty.', 'warning'); return; } const btn = form.find('button[type="submit"]'); const btnTxt = btn.html(); btn.prop('disabled', true).html('<span class="spinner-border spinner-border-sm"></span> Posting...'); apiRequest('POST', '/comments/', { post: postId, parent: parentId, content: content }).done(c => { form.find('textarea').val(''); loadComments(postId); if (parentId) { form.closest('.reply-form-container').slideUp(function(){ $(this).empty(); }); } }).fail(() => {}).always(() => btn.prop('disabled', false).html(btnTxt)); }
export function handleReplyButtonClick(event) { if (!auth.checkAuthStatus()) { navigateTo('#login'); return; } const btn = $(event.target).closest('.btn-reply'); const cDiv = btn.closest('.comment'); const cId = cDiv.data('comment-id'); const pId = $('#comments-section #comment-form-main').data('post-id'); const replyCont = cDiv.find('.reply-form-container').first(); if (!pId || !cId || !replyCont.length) return; $('.reply-form-container').not(replyCont).slideUp(function(){ $(this).empty(); }); if (replyCont.is(':visible')) { replyCont.slideUp(function(){ $(this).empty(); }); } else { replyCont.html(renderCommentForm(pId, cId)).slideDown().find('textarea').focus(); } }
export function handleCancelReply(event) { $(event.target).closest('.reply-form-container').slideUp(function(){ $(this).empty(); }); }
export function handleDeleteComment(event) { if (!auth.checkAuthStatus()) { navigateTo('#login'); return; } const btn = $(event.target).closest('.btn-delete-comment'); const cId = btn.data('comment-id'); const cElem = btn.closest('.comment'); const pId = $('#comments-section #comment-form-main').data('post-id'); if (!cId) return; if (confirm('Delete comment?')) { btn.prop('disabled', true); apiRequest('DELETE', `/comments/${cId}/`).done(() => { showAlert('Comment deleted.', 'success'); if(pId) { loadComments(pId); } else { cElem.fadeOut(300, function() { $(this).remove(); }); const countSpan = $('#comment-count-detail'); if (countSpan.length) { countSpan.text(Math.max(0, (parseInt(countSpan.text())||1)-1)); } } }).fail(() => btn.prop('disabled', false)); } }
