
import $ from 'jquery';
import { apiRequest } from '../core/api.js';
import * as auth from '../core/auth.js';
import { showAlert } from '../ui/common.js';
import { renderProfile } from '../ui/profile.js';

export function handleProfileUpdate(event) { event.preventDefault(); if (!auth.checkAuthStatus()) return; const bio = $('#profile-bio').val(); const $button = $(event.target).find('button[type="submit"]'); const btnTxt = $button.html(); $button.prop('disabled', true).html('<span class="spinner-border spinner-border-sm"></span> Updating...'); apiRequest('PATCH', '/profile/', { bio: bio }).done(user => { showAlert('Profile updated.', 'success'); renderProfile(user); }).fail(() => {}).always(() => $button.prop('disabled', false).html(btnTxt)); }
export function handleAvatarUpload(event) { event.preventDefault(); if (!auth.checkAuthStatus()) return; const input = document.getElementById('avatar-input'); const $button = $(event.target).find('button[type="submit"]'); const btnTxt = $button.html(); if (!input.files.length) { showAlert('Select image file.', 'warning'); return; } const formData = new FormData(); formData.append('avatar', input.files[0]); $button.prop('disabled', true).html('<span class="spinner-border spinner-border-sm"></span> Uploading...'); apiRequest('PATCH', '/profile/', formData, true, true).done(user => { showAlert('Avatar updated.', 'success'); renderProfile(user); }).fail(() => {}).always(() => $button.prop('disabled', false).html(btnTxt)); }
export function handleChangePassword(event) { event.preventDefault(); if (!auth.checkAuthStatus()) return; const current = $('#current-password').val(); const newPass = $('#new-password').val(); const confirm = $('#confirm-password').val(); const $button = $(event.target).find('button[type="submit"]'); const btnTxt = $button.html(); if (newPass !== confirm) { showAlert('Passwords do not match.', 'warning'); return; } if (!newPass) { showAlert('New password empty.', 'warning'); return; } $button.prop('disabled', true).html('<span class="spinner-border spinner-border-sm"></span> Changing...'); apiRequest('POST', '/change-password/', { current_password: current, new_password: newPass }).done(() => { showAlert('Password changed. Logging out.', 'success'); auth.handleLogout(); }).fail(() => {}).always(() => $button.prop('disabled', false).html(btnTxt)); }
