
import $ from 'jquery';
import * as api from './core/api.js';
import * as auth from './core/auth.js';
import * as uiCommon from './ui/common.js';
import * as uiNavbar from './ui/navbar.js';
import * as uiPosts from './ui/posts.js';
import * as uiComments from './ui/comments.js';
import * as uiForms from './ui/forms.js';
import * as uiProfile from './ui/profile.js';
import * as uiAdmin from './ui/admin.js';
import * as profileHandlers from './handlers/profileHandlers.js';
import * as postHandlers from './handlers/postHandlers.js';
import * as commentHandlers from './handlers/commentHandlers.js';
import * as adminHandlers from './handlers/adminHandlers.js';
import Editor from '@toast-ui/editor';

let currentEditorInstance = null;
function destroyEditor() { if (currentEditorInstance) { try { currentEditorInstance.destroy(); } catch(e){} currentEditorInstance = null; window.editorInstance = null; } }
function initializeEditor(content = '') { destroyEditor(); try { const el = document.querySelector('#toastui-editor'); if (!el) return; currentEditorInstance = new Editor({ el, height: '400px', initialEditType: 'markdown', previewStyle: 'vertical', initialValue: content, linkAttributes: { target: '_blank', rel: 'noopener noreferrer' } }); window.editorInstance = currentEditorInstance; } catch (e) { $('#toastui-editor').html('<p class="text-danger">Editor load error.</p>'); } }
function loadHomepage(limit, offset) { uiCommon.contentArea.html('<h2>Posts</h2><div id="post-list">Loading...</div><div id="pagination-controls"></div>'); api.apiRequest('GET', `/posts/?limit=${limit}&offset=${offset}`).done(d => { uiPosts.renderPostList(d.results||[],"Posts"); uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,'#/') }).fail(() => uiCommon.contentArea.html('<p>Error</p>')); }
function loadPostDetail(slug) { uiCommon.contentArea.html('<div class="text-center mt-5 spinner-border"></div>'); api.apiRequest('POST', `/posts/${slug}/view/`,null,false).fail(e=>console.warn("View fail")); api.apiRequest('GET', `/posts/${slug}/`).done(p => { uiPosts.renderFullPost(p); loadComments(p.id); }).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
export function loadComments(postId) { const list = $('#comments-list'); if(!list.length) return; list.html('<small>Loading...</small>'); api.apiRequest('GET', `/comments/by_post/?post_id=${postId}`).done(d => uiComments.renderComments(d,postId)).fail(()=>list.html('<p><small>Error</small></p>')); }
function loadMyPosts(limit, offset) { if (!auth.checkAuthStatus()){navigateTo('#login');return;} uiCommon.contentArea.html('<h2>My Posts</h2><div id="post-list">Loading...</div><div id="pagination-controls"></div>'); api.apiRequest('GET', `/posts/my_posts/?limit=${limit}&offset=${offset}`).done(d=>{uiPosts.renderPostList(d.results||[], "My Posts"); uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,'#my-posts')}).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadSavedPosts(limit, offset) { if (!auth.checkAuthStatus()){navigateTo('#login');return;} uiCommon.contentArea.html('<h2>Saved</h2><div id="post-list">Loading...</div><div id="pagination-controls"></div>'); api.apiRequest('GET', `/posts/saved/?limit=${limit}&offset=${offset}`).done(d=>{uiPosts.renderPostList(d.results||[], "Saved"); uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,'#saved-posts')}).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadPostsBy(type, value, limit, offset) { let ep='', title='', base=''; switch(type){ case 'category': ep=`/posts/by_category/?slug=${value}`;title=`Category: ${value}`;base=`#posts/by_category/${value}`;break; case 'tag': ep=`/posts/by_tag/?name=${value}`;title=`Tag: ${value}`;base=`#posts/by_tag/${value}`;break; case 'user': ep=`/posts/by_user/?username=${value}`;title=`User: ${value}`;base=`#posts/by_user/${value}`;break; default:navigateTo('#/');return;} ep+=`&limit=${limit}&offset=${offset}`; uiCommon.contentArea.html(`<h2>${title}</h2><div id="post-list">Loading...</div><div id="pagination-controls"></div>`); api.apiRequest('GET',ep).done(d=>{uiPosts.renderPostList(d.results||[],title);uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,base)}).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadProfilePage() { if(!auth.checkAuthStatus()){navigateTo('#login');return;} uiCommon.contentArea.html('<div class="text-center mt-5 spinner-border"></div>'); api.apiRequest('GET', '/profile/').done(u=>uiProfile.renderProfile(u)).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadCreateEditForm(slug=null) { if(!auth.checkAuthStatus()){navigateTo('#login');return;} if(!auth.canCreatePost()&&!slug){uiCommon.showAlert('Denied.','warning');navigateTo('#/');return;} const isEdit=slug!==null; const title=isEdit?'Edit Post':'Create'; uiCommon.contentArea.html(`<h2>${title}</h2><div id="form-container">${uiForms.renderPostForm([],[])}</div>`); Promise.all([api.apiRequest('GET','/categories/?limit=1000'), api.apiRequest('GET','/tags/?limit=1000')]).then(([catRes,tagRes])=>{ const cats=catRes.results||catRes||[]; const tags=tagRes.results||tagRes||[]; if(isEdit){ api.apiRequest('GET',`/posts/${slug}/`).done(pD=>{ if(!auth.canEditOrDelete(pD)){uiCommon.showAlert('Denied.','danger');navigateTo(`#posts/${slug}`);return;} $('#form-container').html(uiForms.renderPostForm(cats,tags,pD)); initializeEditor(pD?.content||''); }).fail(()=>$('#form-container').html('<p>Error</p>')); } else { $('#form-container').html(uiForms.renderPostForm(cats,tags)); initializeEditor(''); } }).catch(()=>$('#form-container').html('<p>Error</p>')); }
export function loadCategoryAdmin() { if(!auth.isAdmin()){navigateTo('#/');return;} uiCommon.contentArea.html('<div class="text-center mt-5 spinner-border"></div>'); api.apiRequest('GET','/categories/?limit=1000').done(d=>uiAdmin.renderCategoryAdminList(d.results||d||[])).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadUserAdmin(limit, offset) { if(!auth.isAdmin()){navigateTo('#/');return;} uiCommon.contentArea.html('<div class="text-center mt-5 spinner-border"></div>'); api.apiRequest('GET',`/users/?limit=${limit}&offset=${offset}`).done(d=>{uiAdmin.renderUserAdminList(d.results||[]);uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,'#admin/users')}).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
function loadTagAdmin(limit, offset) { if(!auth.isAdmin()){navigateTo('#/');return;} uiCommon.contentArea.html('<div class="text-center mt-5 spinner-border"></div>'); api.apiRequest('GET',`/tags/?limit=${limit}&offset=${offset}`).done(d=>{uiAdmin.renderTagAdminList(d.results||[]);uiCommon.renderPagination('#pagination-controls',d.count,limit,offset,'#admin/tags')}).fail(()=>uiCommon.contentArea.html('<p>Error</p>')); }
export function navigateTo(hash) { if(window.location.hash!==hash){window.location.hash=hash;}else{handleHashChange();} }
export function handleHashChange() { destroyEditor(); uiCommon.alertContainer.empty(); uiCommon.contentArea.off().empty().html('<div class="text-center mt-5 spinner-border"></div>'); const hash=window.location.hash||'#/'; if(hash==='#main-content'){uiCommon.contentArea.html('');$('#main-content').attr('tabindex',-1).focus();return;} const parts=hash.substring(1).split('?'); const path=parts[0]; const qs=parts[1]; const pathParts=path.split('/'); const route=pathParts[0]||'home'; const p1=pathParts[1]; const p2=pathParts[2]; const params={}; if(qs){qs.split('&').forEach(p=>{const[k,v]=p.split('=');if(k)params[k]=decodeURIComponent(v||'');});} const offset=parseInt(params.offset)||0; const limit=parseInt(params.limit)||10; switch(route){ case 'home':loadHomepage(limit,offset);attachPostListActionHandlers();break; case 'posts': if(!p1){loadHomepage(limit,offset);attachPostListActionHandlers();} else if(p1==='by_category'&&p2){loadPostsBy('category',p2,limit,offset);attachPostListActionHandlers();} else if(p1==='by_tag'&&p2){loadPostsBy('tag',p2,limit,offset);attachPostListActionHandlers();} else if(p1==='by_user'&&p2){loadPostsBy('user',p2,limit,offset);attachPostListActionHandlers();} else{loadPostDetail(p1);attachPostDetailActionHandlers();} break; case 'login':if(auth.checkAuthStatus()){navigateTo('#/');break;}uiForms.renderLoginForm();attachAuthHandlers();break; case 'register':if(auth.checkAuthStatus()){navigateTo('#/');break;}uiForms.renderRegisterForm();attachAuthHandlers();break; case 'logout':auth.handleLogout();break; case 'profile':if(!auth.checkAuthStatus()){navigateTo('#login');break;}loadProfilePage();attachProfilePageHandlers();break; case 'my-posts':if(!auth.checkAuthStatus()){navigateTo('#login');break;}loadMyPosts(limit,offset);attachPostListActionHandlers();break; case 'saved-posts':if(!auth.checkAuthStatus()){navigateTo('#login');break;}loadSavedPosts(limit,offset);attachPostListActionHandlers();break; case 'create-post':if(!auth.checkAuthStatus()){navigateTo('#login');break;}loadCreateEditForm();attachPostFormHandlers();break; case 'edit-post':if(!auth.checkAuthStatus()){navigateTo('#login');break;}if(p1){loadCreateEditForm(p1);attachPostFormHandlers();}else{navigateTo('#/');}break; case 'admin':if(!auth.isAdmin()){navigateTo('#/');break;}if(p1==='categories'){loadCategoryAdmin();attachCategoryAdminHandlers();}else if(p1==='users'){loadUserAdmin(limit,offset);}else if(p1==='tags'){loadTagAdmin(limit,offset);}else{navigateTo('#/');}break; default:uiCommon.contentArea.html('<h2 class="text-center mt-5">404</h2>');} updateActiveNavLink(hash); const navCollapse=document.getElementById('navbarNav'); if(navCollapse?.classList.contains('show')){bootstrap.Collapse.getInstance(navCollapse)?.hide();} }
function updateActiveNavLink(hash) { $('.navbar-nav .nav-link, .navbar-nav .dropdown-toggle').removeClass('active').removeAttr('aria-current'); const base=hash.split('?')[0]; let $link=$(`.navbar-nav .nav-link[href="${base}"]`); if(!$link.length){const route=base.substring(1).split('/')[0]||'home';const baseRoute=`#${route}`;$link=$(`.navbar-nav .nav-link[href="${baseRoute}"]`);if(!$link.length){$link=$(`.navbar-nav .nav-link[href^="${baseRoute}/"]`);}} if(!$link.length&&(base==='#/'||base==='#')){$link=$('.navbar-nav .nav-link[href="#/"]');} if($link.length){const link=$link.first();link.addClass('active').attr('aria-current','page');link.closest('.dropdown').find('.nav-link.dropdown-toggle').addClass('active');}}
function attachPostListActionHandlers() { uiCommon.contentArea.on('click.postList','.btn-like',postHandlers.handleLikeToggle); uiCommon.contentArea.on('click.postList','.btn-save',postHandlers.handleSaveToggle); uiCommon.contentArea.on('click.postList','.btn-delete-post',postHandlers.handleDeletePost); }
function attachPostDetailActionHandlers() { uiCommon.contentArea.on('submit.postDetail','.comment-form',commentHandlers.handleCommentSubmit); uiCommon.contentArea.on('click.postDetail','.btn-reply',commentHandlers.handleReplyButtonClick); uiCommon.contentArea.on('click.postDetail','.btn-cancel-reply',commentHandlers.handleCancelReply); uiCommon.contentArea.on('click.postDetail','.btn-delete-comment',commentHandlers.handleDeleteComment); uiCommon.contentArea.on('click.postDetail','.btn-like',postHandlers.handleLikeToggle); uiCommon.contentArea.on('click.postDetail','.btn-save',postHandlers.handleSaveToggle); uiCommon.contentArea.on('click.postDetail','.btn-delete-post',postHandlers.handleDeletePost); }
function attachProfilePageHandlers() { uiCommon.contentArea.on('submit.profile','#profile-update-form',profileHandlers.handleProfileUpdate); uiCommon.contentArea.on('submit.profile','#change-password-form',profileHandlers.handleChangePassword); uiCommon.contentArea.on('submit.profile','#avatar-upload-form',profileHandlers.handleAvatarUpload); }
function attachCategoryAdminHandlers() { uiCommon.contentArea.on('click.adminCat','#add-category-btn',()=>{const fc=$('#category-form-container');if(!fc.is(':visible')){fc.html(uiForms.renderCategoryForm()).slideDown().find('#category-name').focus();}}); uiCommon.contentArea.on('click.adminCat','#cancel-category-form',e=>{const formHtml=uiForms.renderCategoryForm();$(e.target).closest('form').parent().slideUp(function(){$(this).empty().html(formHtml).hide();});}); uiCommon.contentArea.on('submit.adminCat','#category-form',adminHandlers.handleCategorySubmit); uiCommon.contentArea.on('click.adminCat','.btn-edit-category',adminHandlers.handleEditCategoryClick); uiCommon.contentArea.on('click.adminCat','.btn-delete-category',adminHandlers.handleDeleteCategory); }
function attachPostFormHandlers() { uiCommon.contentArea.on('submit.postForm','#post-form',postHandlers.handlePostSubmit); }
function attachAuthHandlers() { uiCommon.contentArea.on('submit.auth','#login-form',auth.handleLogin); uiCommon.contentArea.on('submit.auth','#register-form',auth.handleRegister); }
