
import $ from 'jquery';
import * as uiCommon from './common.js';
import * as auth from '../core/auth.js';
import { renderCommentForm } from './comments.js';
import { apiRequest } from '../core/api.js';

export function renderPostList(posts, title = "Posts") {
    uiCommon.contentArea.html(`<h2>${title}</h2><div id="post-list" class="mb-3">Loading...</div><div id="pagination-controls"></div>`);
    const postListContainer = $('#post-list');
    if (posts && posts.length > 0) { postListContainer.empty(); posts.forEach(post => postListContainer.append(renderPostSummary(post))); }
    else { postListContainer.html('<p>No posts found.</p>'); }
    checkAllLikeSaveStatus(posts.map(p=>p.slug));
}

function renderPostSummary(post) {
    const summaryLength = 200; let excerpt = '';
    if (post.content) { const cleanHtml = uiCommon.sanitizeAndParseMarkdown(post.content); const tempDiv = $('<div>').html(cleanHtml); const textContent = tempDiv.text(); excerpt = textContent.length > summaryLength ? textContent.substring(0, summaryLength) + '...' : textContent; }
    const canModify = auth.canEditOrDelete(post); const postDate = post.created_at ? new Date(post.created_at).toLocaleDateString() : 'N/A';
    return ` <div class="card post-summary mb-4" data-slug="${post.slug}"> ${post.featured_image_url ? `<a href="#posts/${post.slug}"><img src="${post.featured_image_url}" class="card-img-top" alt="${post.title}" style="max-height: 250px; object-fit: cover;"></a>` : ''} <div class="card-body"> <h3 class="card-title mb-1"><a href="#posts/${post.slug}" class="text-decoration-none">${post.title || 'Untitled'}</a></h3> <p class="post-meta card-subtitle mb-2 text-muted"> <i class="bi bi-person"></i> <a href="#posts/by_user/${post.author}" class="text-muted text-decoration-none">${post.author || '?'}</a> <i class="bi bi-calendar-event ms-2"></i> ${postDate} ${post.category ? `<i class="bi bi-folder ms-2"></i> <a href="#posts/by_category/${post.category}" class="text-muted text-decoration-none">${post.category}</a>` : ''} <br class="d-sm-none"> <span class="ms-sm-2"><i class="bi bi-chat-dots"></i> ${post.comment_count ?? 'N/A'}</span> <span class="ms-2"><i class="bi bi-eye"></i> ${post.view_count ?? 'N/A'}</span> <span class="ms-2"><i class="bi bi-hand-thumbs-up"></i> <span class="like-count">${post.likes?.length || 0}</span></span> </p> <p class="card-text">${excerpt || ''}</p> <div class="mb-2"> ${post.tags?.length > 0 ? '<i class="bi bi-tags me-1"></i>' : ''} ${(post.tags || []).map(tag => `<a href="#posts/by_tag/${tag}" class="tag">${tag}</a>`).join('')} </div> <a href="#posts/${post.slug}" class="btn btn-sm btn-outline-primary mt-1"><i class="bi bi-book me-1"></i>Read More</a> ${auth.getCurrentUser().token ? `<button class="btn btn-sm btn-outline-danger mt-1 btn-like" data-slug="${post.slug}" data-liked="false"><i class="bi bi-heart"></i><i class="bi bi-heart-fill"></i> Like</button> <button class="btn btn-sm btn-outline-success mt-1 btn-save" data-slug="${post.slug}" data-saved="false"><i class="bi bi-bookmark"></i><i class="bi bi-bookmark-fill"></i> Save</button>` : ''} ${ canModify ? `<a href="#edit-post/${post.slug}" class="btn btn-sm btn-outline-warning mt-1"><i class="bi bi-pencil"></i> Edit</a> <button class="btn btn-sm btn-outline-danger mt-1 btn-delete-post" data-slug="${post.slug}"><i class="bi bi-trash"></i> Delete</button>` : ''} </div> </div>`;
}

export function renderFullPost(post) {
    const canModify = auth.canEditOrDelete(post); const postContentHtml = uiCommon.sanitizeAndParseMarkdown(post.content); const postDate = post.created_at ? new Date(post.created_at).toLocaleDateString() : 'N/A'; const commentFormHtml = renderCommentForm(post.id);
    const postHtml = ` <article class="card"> <div class="card-body"> ${post.featured_image_url ? `<img src="${post.featured_image_url}" class="img-fluid rounded mb-3 mx-auto d-block" alt="${post.title}" style="max-height: 400px;">` : ''} <h1 class="card-title">${post.title || 'Untitled'}</h1> <p class="post-meta text-muted mb-3"> <i class="bi bi-person"></i> <a href="#posts/by_user/${post.author}" class="text-muted text-decoration-none">${post.author || '?'}</a> <i class="bi bi-calendar-event ms-2"></i> ${postDate} ${post.category ? `<i class="bi bi-folder ms-2"></i> <a href="#posts/by_category/${post.category}" class="text-muted text-decoration-none">${post.category}</a>` : ''} <br> <span class="ms-0"><i class="bi bi-chat-dots"></i> <span id="comment-count-detail">${post.comment_count ?? 'N/A'}</span> comments</span> <span class="ms-2"><i class="bi bi-eye"></i> ${post.view_count ?? 'N/A'} views</span> <span class="ms-2"><i class="bi bi-hand-thumbs-up"></i> <span id="like-count">${post.likes?.length || 0}</span> Likes</span> </p> <div id="post-content" class="mb-4">${postContentHtml}</div> <div class="mb-3"> ${post.tags?.length > 0 ? '<i class="bi bi-tags me-1"></i>' : ''} ${(post.tags || []).map(tag => `<a href="#posts/by_tag/${tag}" class="tag">${tag}</a>`).join('')} </div> <div class="d-flex flex-wrap gap-2 border-top pt-3"> ${auth.getCurrentUser().token ? `<button class="btn btn-outline-danger btn-like" data-slug="${post.slug}" data-liked="false"><i class="bi bi-heart"></i><i class="bi bi-heart-fill"></i> Like</button> <button class="btn btn-outline-success btn-save" data-slug="${post.slug}" data-saved="false"><i class="bi bi-bookmark"></i><i class="bi bi-bookmark-fill"></i> Save</button>` : ''} ${ canModify ? `<a href="#edit-post/${post.slug}" class="btn btn-warning"><i class="bi bi-pencil"></i> Edit</a> <button class="btn btn-danger btn-delete-post" data-slug="${post.slug}"><i class="bi bi-trash"></i> Delete</button>` : ''} <a href="#/" class="btn btn-secondary ms-auto"><i class="bi bi-arrow-left"></i> Back</a> </div> </div> </article> <hr> <section id="comments-section" class="mt-4"> <h3>Comments</h3> <div id="comments-list" class="mb-4">Loading...</div> ${auth.getCurrentUser().token ? commentFormHtml : '<p><a href="#login">Log in</a> or <a href="#register">register</a> to comment.</p>'} </section> `;
    uiCommon.contentArea.html(postHtml); checkAllLikeSaveStatus([post.slug]);
}

export function updateLikeButton(slug, liked, likeCount) { const button = $(`.btn-like[data-slug="${slug}"]`); if (!button.length) return; button.toggleClass('liked', liked).data('liked', liked); const countSpan = button.closest('.card-body, .pt-3').find('.like-count, #like-count'); if(countSpan.length) countSpan.text(likeCount); }
export function updateSaveButton(slug, saved) { const button = $(`.btn-save[data-slug="${slug}"]`); if (!button.length) return; button.toggleClass('saved', saved).data('saved', saved); }
export function checkAllLikeSaveStatus(postSlugs) { if (!auth.getCurrentUser().token || !postSlugs?.length) return; apiRequest('GET', '/posts/saved/?limit=1000').done(data => { const savedResults = data.results || data || []; const savedSlugs = new Set(savedResults.map(p => p.slug)); postSlugs.forEach(slug => updateSaveButton(slug, savedSlugs.has(slug))); }).fail(err => {}); }
export function renderFooter(recentPosts, popularTags, stats) { const recentList = $('#footer-recent-posts'); const tagsList = $('#footer-popular-tags'); const statsList = $('#footer-site-stats'); recentList.empty(); if (recentPosts?.length) { recentPosts.forEach(p => recentList.append(`<li><a href="#posts/${p.slug}" class="text-decoration-none text-muted">${p.title}</a></li>`)); } else { recentList.html('<li class="text-muted small">No posts.</li>'); } tagsList.empty(); if (popularTags?.length) { popularTags.forEach(t => tagsList.append(`<a href="#posts/by_tag/${t.name}" class="tag me-1 mb-1">${t.name} (${t.post_count})</a> `)); } else { tagsList.html('<li class="text-muted small">No tags.</li>'); } statsList.empty(); if (stats) { statsList.append(`<li class="text-muted"><i class="bi bi-file-earmark-text me-1"></i> Posts: ${stats.total_posts||0} (${stats.published_posts||0})</li>`); statsList.append(`<li class="text-muted"><i class="bi bi-chat-dots me-1"></i> Comments: ${stats.total_comments||0}</li>`); statsList.append(`<li class="text-muted"><i class="bi bi-folder me-1"></i> Categories: ${stats.total_categories||0}</li>`); statsList.append(`<li class="text-muted"><i class="bi bi-tags me-1"></i> Tags: ${stats.total_tags||0}</li>`); } else { statsList.html('<li class="text-muted small">No stats.</li>'); } }
